sjobs:
  - { git_repo_url: https://github.com/bdevops99b/roboshop-terraform.git, job_name: roboshop-terraform }
  - { git_repo_url: https://github.com/bdevops99b/roboshop-ansible.git, job_name: roboshop-ansible }
  - { git_repo_url: https://github.com/bdevops99b/ws-ssm-parameter-store.git, job_name: ws-ssm-parameter-store }
  - { git_repo_url: https://github.com/bdevops99b/roboshop-helm.git, job_name: roboshop-ansible }

mjobs:
  - { git_repo_url: https://github.com/bdevops99b/cart.git, job_name: cart }
  - { git_repo_url: https://github.com/bdevops99b/catalogue.git, job_name: catalogue }
  - { git_repo_url: https://github.com/bdevops99b/user.git, job_name: user }
  - { git_repo_url: https://github.com/bdevops99b/shipping.git, job_name: shipping }
  - { git_repo_url: https://github.com/bdevops99b/payment.git, job_name: payment }
  - { git_repo_url: https://github.com/bdevops99b/dispatch.git, job_name: dispatch }
  - { git_repo_url: https://github.com/bdevops99b/frontend.git, job_name: frontend}


