sjobs:
  - { git_repo_url: https://github.com/bdevops99b/roboshop-terraform.git, job_name: roboshop-terraform }
  - { git_repo_url: https://github.com/bdevops99b/roboshop-ansible.git, job_name: roboshop-ansible }